### ISSUE TITLE
Sonar.ada.gnathub.db is not defined

### ISSUE THREAD

**Issue by Saeed-ghub** [AdaCore/gnatdashboard#12]
Hi,

I am trying to perform code analysis.
I have using sonar scanner 4.0 and Sonar Comm. version 7.9.3

The code analysis results are not getting to the SonarQube.dashboard

I will include extract of the logs. this is mainly after the scanner -X has been called.

There is a mixture of C++ and ADA code here.
The ADA side seems to be causing the issue at this moment…

3:28:45.672 INFO: Sensor Ada Code Highlighting Sensor [ada] (done) | time=1876ms
13:28:45.672 INFO: Sensor GNAThub Issues Import [ada]
13:28:45.940 INFO: ------------------------------------------------------------------------
13:28:45.940 INFO: EXECUTION FAILURE
13:28:45.940 INFO: ------------------------------------------------------------------------
13:28:45.941 INFO: Total time: 1:53.327s
13:28:46.068 INFO: Final Memory: 32M/120M
13:28:46.068 INFO: ------------------------------------------------------------------------
13:28:46.069 ERROR: Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: sonar.ada.gnathub.db is not defined in the project properties file
at org.sonar.plugins.ada.GNAThub.(GNAThub.java:46)

Any Ideas?

Thanks

**Comment by setton** [comment]
Hello Saeed,

We'll need way more data than this in order to understand the problem. Closing the issue pending this.

Best regards,

Nicolas

**Comment by Saeed-ghub** [comment]
Hi Nicolas,

It is difficult for me to know what you are referring to as the emails cut out all other messages except yours.
The gnatmetric file was requested this morning and I have sent this on to your team.

Also if you could send emails to my Thales account regarding this?

Thanks
Saeed

**Comment by setton** [comment]
Hello @Saeed-ghub - I don't understand your statement regarding the emails issue. But let's follow this up under AdaCore customer support.

**Comment by Saeed-ghub** [comment]
Ah yes, thi was an issue that I had in the early days and I only had GitHub in mind to contact Ada issues.

Ok you can close this.

Regards
Saeed
